function normalizePhone(phone) {
  if (!phone) return null;
  const value = String(phone).trim();
  if (value.startsWith("+")) return value;
  const digits = value.replace(/\D/g, "");
  if (digits.length === 10) return "+91" + digits;
  return digits ? "+" + digits : null;
}

function buildAlertMessage({ touristName, type, latitude, longitude }) {
  const location = latitude != null && longitude != null
    ? `https://maps.google.com/?q=${latitude},${longitude}`
    : "Location unavailable";

  if (type === "SOS") {
    return `URGENT: SafarSuraksha SOS for ${touristName || "tourist"}. Current location: ${location}. Please contact the tourist or emergency services immediately.`;
  }

  return `SafarSuraksha alert for ${touristName || "tourist"}: ${type.replaceAll("_", " ")}. Current location: ${location}.`;
}

async function sendTwilioSms(to, body) {
  const accountSid = process.env.TWILIO_ACCOUNT_SID;
  const authToken = process.env.TWILIO_AUTH_TOKEN;
  const from = process.env.TWILIO_FROM;
  const messagingServiceSid = process.env.TWILIO_MESSAGING_SERVICE_SID;

  if (!accountSid || !authToken || (!from && !messagingServiceSid) || !to) {
    return { sent: false, configured: false, channel: "sms" };
  }

  const params = new URLSearchParams({ To: normalizePhone(to), Body: body });
  if (messagingServiceSid) params.set("MessagingServiceSid", messagingServiceSid);
  else params.set("From", normalizePhone(from));

  const auth = Buffer.from(`${accountSid}:${authToken}`).toString("base64");
  const response = await fetch(
    `https://api.twilio.com/2010-04-01/Accounts/${accountSid}/Messages.json`,
    {
      method: "POST",
      headers: {
        Authorization: `Basic ${auth}`,
        "Content-Type": "application/x-www-form-urlencoded",
      },
      body: params,
    }
  );

  const text = await response.text();
  if (!response.ok) throw new Error(`Twilio SMS failed: HTTP ${response.status} ${text.slice(0, 180)}`);

  return { sent: true, configured: true, channel: "sms" };
}

async function sendZeptoMail(to, subject, htmlbody) {
  const apiKey = process.env.ZEPTO_MAIL_API_KEY;
  const from = process.env.ZEPTO_FROM_EMAIL;

  if (!apiKey || !from || !to) {
    return { sent: false, configured: false, channel: "email" };
  }

  const response = await fetch(
    process.env.ZEPTO_MAIL_URL || "https://api.zeptomail.com/v1.1/email",
    {
      method: "POST",
      headers: {
        Accept: "application/json",
        "Content-Type": "application/json",
        Authorization: `Zoho-enczapikey ${apiKey}`,
      },
      body: JSON.stringify({
        from: { address: from, name: process.env.ZEPTO_FROM_NAME || "SafarSuraksha" },
        to: [{ email_address: { address: to } }],
        subject,
        htmlbody,
      }),
    }
  );

  const text = await response.text();
  if (!response.ok) throw new Error(`ZeptoMail failed: HTTP ${response.status} ${text.slice(0, 180)}`);

  return { sent: true, configured: true, channel: "email" };
}

async function notifyEmergencyContact({ tourist, type, latitude, longitude }) {
  if (!tourist) return { sms: { sent: false, configured: false }, email: { sent: false, configured: false } };

  const message = buildAlertMessage({
    touristName: tourist.name,
    type,
    latitude,
    longitude,
  });

  const results = await Promise.allSettled([
    sendTwilioSms(tourist.emergencyContact, message),
    sendZeptoMail(
      tourist.email,
      `SafarSuraksha ${type.replaceAll("_", " ")} alert`,
      `<h2>SafarSuraksha Alert</h2><p>${message}</p><p>This notification was generated by the active journey safety system.</p>`
    ),
  ]);

  return {
    sms: results[0].status === "fulfilled" ? results[0].value : { sent: false, configured: true, error: results[0].reason?.message },
    email: results[1].status === "fulfilled" ? results[1].value : { sent: false, configured: true, error: results[1].reason?.message },
  };
}

module.exports = { notifyEmergencyContact, normalizePhone };